### ISSUE TITLE
"approval_date" throws error in geolink_formatter

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/geolink_formatter#56]
Hi

we get an error, when trying to access an OEREBLex document, which has an "approval_date" set, see error message:

"lxml.etree.XMLSyntaxError: Element 'document', attribute 'approval_date': The attribute 'approval_date' is not allowed."

Unfortunately, the approval_date is set for many documents uploaded to OEREBLex already.
Is there a way to work around this? 
Is one option to just add the attribute to the v1.1.1.xsd file like this:
						<xs:attribute name="approval_date" type="xs:string"/>
Or will this bring problems? 

Thanks & Regards
Max

![Approval_Date](https://user-images.githubusercontent.com/54711581/66112886-f69b3780-e5cb-11e9-8a2a-2f0285358ad2.jpg)

**Comment by MaxHoeferGEOINFO** [comment]
Hello,

could I get a reply to this please?
Thanks
Max

**Comment by kdeininger** [comment]
@tschoppi, is this also a manual override, as done at https://github.com/openoereb/pyramid_oereb/issues/903?

If this is the case, are there any other overrides that might cause errors on validating the geoLink XML against its schema?

**Comment by tschoppi** [comment]
@kdeininger, I found the following fields that are not yet specified in the XSD:
- `publication_date`
- `approval_date`
- `cycle`

All of them are of type `xs:string`.

The presence of these attributes is dependent on the corresponding configuration of the OEREBlex instance. So not a manual override in a strict sense, but including them in the schema should not pose any problems.

**Comment by kdeininger** [comment]
@tschoppi, thanks for your reply. I will add these properties and create a new release.
