### ISSUE TITLE
Error: " lxml.etree.DocumentInvalid: Element 'document', attribute 'language': The attribute 'language' is not allowed., line 3"

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/geolink_formatter#73]
Hi

I tested our Oereb-Portal today, since Sitrox updated yesterday - now I get the following error message, when I send a pyramid_oereb request:

" lxml.etree.DocumentInvalid: Element 'document', attribute 'language': The attribute 'language' is not allowed., line 3"
I assume this relates to https://github.com/openoereb/pyramid_oereb/issues/923 ? 

I checked the oereblex document, and I do not see any language set there - see screenshot attached. 
![Link](https://user-images.githubusercontent.com/54711581/71236016-18b87200-22fe-11ea-90da-39005b750843.png)

What do I have to change/do to get this working? 

Here also the full error message:
[Fri Dec 20 07:35:03.581399 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167] 2019-12-20 07:35:03,581 DEBUG [pyramid_oereb.contrib.sources.document][Dummy-1] read() getting documents, url: https://oereblex.ai.ch//api/geolinks/249.xml, parser: <geolink_formatter.parser.XML object at 0x7f355c708ac8>
[Fri Dec 20 07:35:04.266688 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167] 2019-12-20 07:35:04,266 INFO  [sqlalchemy.engine.base.Engine][Dummy-1] ROLLBACK
[Fri Dec 20 07:35:04.266765 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167] 2019-12-20 07:35:04,266 INFO  [sqlalchemy.engine.base.Engine][Dummy-1] ROLLBACK
[Fri Dec 20 07:35:04.267891 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167] mod_wsgi (pid=12438): Exception occurred processing WSGI script '/var/www/html/ktai/apache/application.wsgi'.
[Fri Dec 20 07:35:04.268243 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167] Traceback (most recent call last):
[Fri Dec 20 07:35:04.268311 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
[Fri Dec 20 07:35:04.268369 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     response = request.invoke_exception_view(exc_info)
[Fri Dec 20 07:35:04.268384 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
[Fri Dec 20 07:35:04.268391 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     raise HTTPNotFound
[Fri Dec 20 07:35:04.268410 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167] pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
[Fri Dec 20 07:35:04.268424 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]
[Fri Dec 20 07:35:04.268455 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167] During handling of the above exception, another exception occurred:
[Fri Dec 20 07:35:04.268461 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]
[Fri Dec 20 07:35:04.268471 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167] Traceback (most recent call last):
[Fri Dec 20 07:35:04.268568 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
[Fri Dec 20 07:35:04.268579 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     response = self.execution_policy(environ, self)
[Fri Dec 20 07:35:04.268594 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
[Fri Dec 20 07:35:04.268600 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     return request.invoke_exception_view(reraise=True)
[Fri Dec 20 07:35:04.268607 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
[Fri Dec 20 07:35:04.268613 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     reraise_(*exc_info)
[Fri Dec 20 07:35:04.268620 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
[Fri Dec 20 07:35:04.268625 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     raise value
[Fri Dec 20 07:35:04.268632 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
[Fri Dec 20 07:35:04.268637 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     return router.invoke_request(request)
[Fri Dec 20 07:35:04.268644 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
[Fri Dec 20 07:35:04.268650 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     response = handle_request(request)
[Fri Dec 20 07:35:04.268657 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
[Fri Dec 20 07:35:04.268662 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     response = _error_handler(request, exc)
[Fri Dec 20 07:35:04.268670 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
[Fri Dec 20 07:35:04.268675 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     reraise(*exc_info)
[Fri Dec 20 07:35:04.268689 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
[Fri Dec 20 07:35:04.268695 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     raise value
[Fri Dec 20 07:35:04.268702 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
[Fri Dec 20 07:35:04.268707 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     response = handler(request)
[Fri Dec 20 07:35:04.268714 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
[Fri Dec 20 07:35:04.268720 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     registry, request, context, context_iface, view_name
[Fri Dec 20 07:35:04.268727 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
[Fri Dec 20 07:35:04.268733 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     response = view_callable(context, request)
[Fri Dec 20 07:35:04.268753 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/config/views.py", line 188, in attr_view
[Fri Dec 20 07:35:04.268763 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     return view(context, request)
[Fri Dec 20 07:35:04.268771 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
[Fri Dec 20 07:35:04.268777 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     return view(context, request)
[Fri Dec 20 07:35:04.268784 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
[Fri Dec 20 07:35:04.268790 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     result = view(context, request)
[Fri Dec 20 07:35:04.268797 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
[Fri Dec 20 07:35:04.268802 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     response = getattr(inst, attr)()
[Fri Dec 20 07:35:04.268809 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/views/webservice.py", line 218, in get_extract_by_id
[Fri Dec 20 07:35:04.268814 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     self._request.route_url('{0}/sld'.format(route_prefix))
[Fri Dec 20 07:35:04.268822 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/lib/processor.py", line 288, in process
[Fri Dec 20 07:35:04.268827 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     extract_raw = self._extract_reader_.read(real_estate, municipality, params)
[Fri Dec 20 07:35:04.268834 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/lib/readers/extract.py", line 147, in read
[Fri Dec 20 07:35:04.268840 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     plr_source.read(real_estate, bbox, position)
[Fri Dec 20 07:35:04.268852 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/standard/sources/plr.py", line 526, in read
[Fri Dec 20 07:35:04.268858 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     legend_entries_from_db
[Fri Dec 20 07:35:04.268865 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/standard/sources/plr.py", line 323, in from_db_to_plr_record
[Fri Dec 20 07:35:04.268870 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     document_records = self.get_document_records(public_law_restriction_from_db)
[Fri Dec 20 07:35:04.268878 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/contrib/sources/plr_oereblex.py", line 43, in get_document_records
[Fri Dec 20 07:35:04.268883 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     return self.document_records_from_oereblex(public_law_restriction_from_db.geolink)
[Fri Dec 20 07:35:04.268890 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/contrib/sources/plr_oereblex.py", line 58, in document_records_from_oereblex
[Fri Dec 20 07:35:04.268896 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     self._oereblex_source.read(lexlink)
[Fri Dec 20 07:35:04.268903 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/contrib/sources/document.py", line 84, in read
[Fri Dec 20 07:35:04.268909 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     documents = self._parser.from_url(url, {}, proxies=self._proxies, auth=self._auth)
[Fri Dec 20 07:35:04.268916 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/geolink_formatter/parser.py", line 173, in from_url
[Fri Dec 20 07:35:04.268921 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     return self.from_string(response.content)
[Fri Dec 20 07:35:04.268928 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/geolink_formatter/parser.py", line 99, in from_string
[Fri Dec 20 07:35:04.268933 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     root = self._parse_xml(xml)
[Fri Dec 20 07:35:04.268940 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/geolink_formatter/parser.py", line 76, in _parse_xml
[Fri Dec 20 07:35:04.268945 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]     self._schema.assertValid(content)
[Fri Dec 20 07:35:04.268952 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167]   File "src/lxml/etree.pyx", line 3569, in lxml.etree._Validator.assertValid
[Fri Dec 20 07:35:04.268970 2019] [wsgi:error] [pid 12438:tid 139867215685376] [remote 172.30.21.144:49167] lxml.etree.DocumentInvalid: Element 'document', attribute 'language': The attribute 'language' is not allowed., line 3

**Comment by MaxHoeferGEOINFO** [comment]
Hi

ah - it seems it's still using the v1.1.1.xsd in my setup, can that be? 
How do I change, that pyramid_oereb is using the new xsd? 

Thanks a lot
Max

**Comment by kdeininger** [comment]
You can specifiy the version of the geoLink API in the configuration of pyramid_oereb:

```yaml
# Configuration for OEREBlex
oereblex:
  # OEREBlex host
  host: https://oereblex.bl.ch
  # geoLink schema version
  version: 1.1.0
  # Pass schema version in URL
  pass_version: true
...
```

https://openoereb.github.io/pyramid_oereb/doc/changes.html#changes-new-config-oereb-lex

If you want to use the latest version (1.2.0), you have to install one of the recent daily builds of pyramid_oereb as it is planned for the next release.

**Comment by kdeininger** [comment]
@MaxHoeferGEOINFO could you solve your problem? The recent release of pyramid_oereb supports the geoLink API, version 1.2.0 and the language attribute.

**Comment by kdeininger** [comment]
@MaxHoeferGEOINFO, I will close this issue now. Please feel free to re-open it or to create a new one, if the problem still occurs.
