### ISSUE TITLE
geolink_formatter crashes when when language is not de

### ISSUE THREAD

**Issue by CoNussberger** [openoereb/geolink_formatter#85]
When using the geolink_formatter with another language than german it crashes because the enumaration values for fedral_level defined in geolink_formatter/schema/v1.2.0.xsd are defined only in german and are translated in the response of oereb-lex.

The following addition to geolink_formatter/schema/v1.2.0.xsd solves the problem for it and rm.

                        <xs:attribute name="federal_level">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Bezirk"/>
                                    <xs:enumeration value="Gemeinde"/>
                                    <xs:enumeration value="Kanton"/>
                                    <xs:enumeration value="Interkantonal"/>
                                    <xs:enumeration value="Bund"/>
                                    <xs:enumeration value="Comune"/>
                                    <xs:enumeration value="Cantone"/>
                                    <xs:enumeration value="Confederazione"/>
                                    <xs:enumeration value="Vischnanca"/>
                                    <xs:enumeration value="Chantun"/>
                                    <xs:enumeration value="Confederaziun"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

**Comment by kdeininger** [comment]
@tschoppi, could you please provide a list with the enumeration values for all supported languages?

**Comment by tschoppi** [comment]
Here is a list of all values that may currently appear in that field:

- A livello intercantonale
- Bezirk
- Bund
- Canton
- Cantone
- Chantun
- Commune
- Comune
- Confédération
- Confederazione
- Confederaziun
- Fürstentum
- Gemeinde
- Intercantonal
- Interchantunal
- Interkantonal
- Kanton
- Vischnanca

You might want to consider softening the validation on that field, as the attribute is translated and translations may vary (e.g. "Bezirk" instead of "Gemeinde").

**Comment by kdeininger** [comment]
Thank you for the list. I have added the additional values in the schema.

It is not possible to exclude elements from validation. But you can turn off validation by setting `xsd_validation=False`. I will propose another change in _pyramid_oereb_ to make this configurable.
