### ISSUE TITLE
UnicodeDecodeError in geolink_formatter when using Oereblex API 1.2.0

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/geolink_formatter#88]
When using the newest version of geolink_formatter, there is a UnicodeDecodeError when reading the XML Schema (this error does not occur in geolink_formatter 1.5.0).

This behaviour was observed by Geoinfo (ktai project) and in Glarus Oereb:

`[Tue May 19 11:46:20.771442 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047] Traceback (most recent call last):
[Tue May 19 11:46:20.771485 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
[Tue May 19 11:46:20.771495 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     response = request.invoke_exception_view(exc_info)
[Tue May 19 11:46:20.771506 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
[Tue May 19 11:46:20.771516 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     raise HTTPNotFound
[Tue May 19 11:46:20.771547 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047] pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
[Tue May 19 11:46:20.771566 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]
[Tue May 19 11:46:20.771574 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047] During handling of the above exception, another exception occurred:
[Tue May 19 11:46:20.771582 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]
[Tue May 19 11:46:20.771594 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047] Traceback (most recent call last):
[Tue May 19 11:46:20.771691 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
[Tue May 19 11:46:20.771716 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     response = self.execution_policy(environ, self)
[Tue May 19 11:46:20.771729 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
[Tue May 19 11:46:20.771735 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     return request.invoke_exception_view(reraise=True)
[Tue May 19 11:46:20.771747 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
[Tue May 19 11:46:20.771756 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     reraise_(*exc_info)
[Tue May 19 11:46:20.771769 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
[Tue May 19 11:46:20.771777 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     raise value
[Tue May 19 11:46:20.771790 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
[Tue May 19 11:46:20.771807 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     return router.invoke_request(request)
[Tue May 19 11:46:20.771826 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
[Tue May 19 11:46:20.771834 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     response = handle_request(request)
[Tue May 19 11:46:20.771845 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
[Tue May 19 11:46:20.771853 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     response = _error_handler(request, exc)
[Tue May 19 11:46:20.771863 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
[Tue May 19 11:46:20.771871 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     reraise(*exc_info)
[Tue May 19 11:46:20.771882 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
[Tue May 19 11:46:20.771890 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     raise value
[Tue May 19 11:46:20.771901 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
[Tue May 19 11:46:20.771909 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     response = handler(request)
[Tue May 19 11:46:20.771920 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
[Tue May 19 11:46:20.771947 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     registry, request, context, context_iface, view_name
[Tue May 19 11:46:20.771958 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
[Tue May 19 11:46:20.771972 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     response = view_callable(context, request)
[Tue May 19 11:46:20.771983 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/config/views.py", line 188, in attr_view
[Tue May 19 11:46:20.771990 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     return view(context, request)
[Tue May 19 11:46:20.772002 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
[Tue May 19 11:46:20.772011 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     return view(context, request)
[Tue May 19 11:46:20.772029 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/contrib/stats/decorators.py", line 9, in wrapper
[Tue May 19 11:46:20.772037 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     response = wrapped(context, request)
[Tue May 19 11:46:20.772049 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
[Tue May 19 11:46:20.772056 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     result = view(context, request)
[Tue May 19 11:46:20.772068 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 111, in _class_requestonly_view
[Tue May 19 11:46:20.772075 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     inst = view(request)
[Tue May 19 11:46:20.772087 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/views/webservice.py", line 33, in __init__
[Tue May 19 11:46:20.772093 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     if not isinstance(request.pyramid_oereb_processor, Processor):
[Tue May 19 11:46:20.772105 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid/decorator.py", line 43, in __get__
[Tue May 19 11:46:20.772111 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     val = self.wrapped(inst)
[Tue May 19 11:46:20.772130 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/__init__.py", line 85, in pyramid_oereb_processor
[Tue May 19 11:46:20.772138 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     init_processor()
[Tue May 19 11:46:20.772149 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/__init__.py", line 125, in init_processor
[Tue May 19 11:46:20.772156 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     plr_sources.append(plr_source_class(**plr))
[Tue May 19 11:46:20.772167 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/custom_code/plr_oereblex.py", line 35, in __init__
[Tue May 19 11:46:20.772174 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     super(DatabaseOEREBlexSourceWithBetterTitle, self).__init__(**kwargs)
[Tue May 19 11:46:20.772186 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/contrib/sources/plr_oereblex.py", line 37, in __init__
[Tue May 19 11:46:20.772200 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     self._oereblex_source = OEREBlexSource(**Config.get_oereblex_config())
[Tue May 19 11:46:20.772211 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/pyramid_oereb/contrib/sources/document.py", line 75, in __init__
[Tue May 19 11:46:20.772225 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     self._parser = XML(host_url=kwargs.get('host'), version=self._version, xsd_validation=xsd_validation)
[Tue May 19 11:46:20.772236 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/var/www/html/ktai/.venv/lib/python3.6/site-packages/geolink_formatter/parser.py", line 51, in __init__
[Tue May 19 11:46:20.772244 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     self._schema = XMLSchema(fromstring(f.read()))
[Tue May 19 11:46:20.772254 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]   File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
[Tue May 19 11:46:20.772262 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047]     return codecs.ascii_decode(input, self.errors)[0]
[Tue May 19 11:46:20.772278 2020] [wsgi:error] [pid 14178:tid 140409566770944] [remote 172.30.21.101:39047] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3163: ordinal not in range(128)`

**Comment by jwkaltz** [comment]
@kdeininger I wonder if the error was introduced by the update of the lxml library. I don't see any other relevant changes between geolink_formatter 1.5.0 and 1.5.1
I will do a PR for a quick-fix, but it's just a work-around for now.

**Comment by jwkaltz** [comment]
@kdeininger are you able to reproduce this error? How are we going to proceed?
The workaround in #89 will work only if XML validation is deactivated (and anyway, it will be available only with a new release of geolink_formatter).

**Comment by kdeininger** [comment]
I could not reproduce the error. We have updated our OEREB Server last week and are now using the latest version of geolink_formatter too. We did not notice any problems with the parsing of the schema.

Additionally, the tests on CI are configured to parse all available versions of the schema using each supported Python version.

Anyway, I am currently merging the latest dependency updates (including lxml) and I will create a new release afterwards containing your PR.

**Comment by jwkaltz** [comment]
OK thanks for the info, I will test the new version at Glarus (with and without schema validation) when available.

**Comment by kdeininger** [comment]
The new release is now available at PyPI:

https://pypi.org/project/geolink-formatter/1.5.2/

**Comment by jwkaltz** [comment]
Starting yesterday's daily build of pyramid_oereb, https://pypi.org/project/pyramid_oereb/1.7.5.dev20200602/ , the new version of geolink_formatter is used.
However, it still has this error (tested on Glarus server). Now, a permanent workaround is available in pyramid_oereb, by setting validation: false in the oereblex section. For now, I will communicate this workaround to Glarus, Geoinfo and Liechtenstein, where this error appears.

Time permitting, I will try to analyse the actual reason for the error (maybe somebody else will have time before me).

**Comment by jwkaltz** [comment]
I have tried to reproduce the error in a local development environment. When using the same oereblex service that Glarus uses in the local development setup (Dockerized) and activating XML schema validation, the error does not appear. I am now suspecting some OS specific setting to be the cause of the error when this code is used on Glarus, Liechtenstein and Geoinfo servers, I will investigate more in this direction.

**Comment by CoNussberger** [comment]
I had / have the same error and found that it is caused by an encoding problem. The xml shema of version 1.2.0 contains "Fürstentum" and "Confédération" and therefore has to use utf-8 as encoding. At least in our setting the file is read as ascii.

One solution for the problem would therefore be to change line 51 of the file geolink_formatter/geolink_formatter/parser.py as follows:

            `with open(xsd, encoding='utf-8') as f:`

But as it works in the dockerized version i guess there should also be a global setting to ensure the correct encoding.

**Comment by jwkaltz** [comment]
Thanks for the infos @CoNussberger !
I therefore propose #105 as a fix. I think this is necessary, because some users run pyramid_oereb as just one of several Apache/WSGI applications, and it should work without needing to change any server settings.

**Comment by jwkaltz** [comment]
@kdeininger Can you please do a new maintenance release of geolink_formatter? This way we can activate the xml schema validation for all sites (after the corresponding pyramid_oereb update)
